services:
  mongo:
    platform: linux/arm64
    image: mongodb/mongodb-community-server:latest
    container_name: mongo
    restart: always
    command: ["--bind_ip_all"]
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGODB_INITDB_DATABASE: nodebb
      NODEBB_USER: nodebb
      NODEBB_PASSWORD: ${MONGO_NODEBB_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network

  nodebb:
    # Using platform emulation to run x86_64 image on ARM64
    platform: linux/amd64
    image: elestio/nodebb:latest
    container_name: nodebb
    restart: always
    depends_on:
      - mongo
    ports:
      - "4567:4567"
    volumes:
      - nodebb_data:/usr/src/app/public/uploads
      - nodebb_build:/usr/src/app/build
      - nodebb_config:/opt/config
      - ./nodebb-init.js:/usr/src/app/nodebb-init.js
    environment:
      - DOMAIN=${DOMAIN}
      - SUBDOMAIN_NODEBB=${SUBDOMAIN_NODEBB}
      - PROTOCOL=${PROTOCOL}
      - NODEBB_PORT=${NODEBB_PORT}
      - NODEBB_SECRET=${NODEBB_SECRET}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_NODEBB_USERNAME=${MONGO_NODEBB_USERNAME}
      - MONGO_NODEBB_PASSWORD=${MONGO_NODEBB_PASSWORD}
      - MONGO_NODEBB_DATABASE=${MONGO_NODEBB_DATABASE}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
    entrypoint: ["/bin/bash", "-c", "chmod +x /usr/src/app/nodebb-init.js && node /usr/src/app/nodebb-init.js"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  nodebb_data:
    driver: local
  nodebb_build:
    driver: local
  nodebb_config:
    driver: local